backend:
  name: github
  repo: crtormen/my-gatsby-blog
  branch: master
  site-domain: https://crtormen.netlify.app

publish_mode: editorial_workflow
media_folder: "static/assets/img"
public_folder: "/assets/img"


collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "image", name: "thumbnail", widget: "image"}
      - {label: "tags", name: "tags", widget: "string"}
      - {label: "Category", 
          name: "category", 
          widget: "select", 
          options: ["No Category","React", "GraphQl", "Machine Learning", "Python", "Gatsby", "Firebase", "PWA"], 
          default: "No Category"
        }
      - {label: "Body", name: "body", widget: "markdown"}